name: sossoldi
description: A wealth management / personal finance / net worth tracking app.

publish_to: 'none'

version: 0.1.2+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.4
  flutter_local_notifications: ^18.0.1
  gap: ^3.0.1
  intl: ^0.19.0
  path: ^1.9.1
  percent_indicator: ^4.2.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqlite3_flutter_libs:
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  flutter_phoenix: ^1.1.1
  csv: ^6.0.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  device_info_plus: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  test: ^1.25.2

flutter:

  uses-material-design: true

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts/SFProText.ttf

  assets:
    - assets/

flutter_native_splash:
  web: false
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    color: "#ffffff"
    image: assets/android12splash.png

flutter_icons:
  android: true
  ios: true
  web:
    generate: false
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  image_path_ios: "assets/iosicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"