name: Android E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android-apk:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Build apk
        run: |
          flutter pub get
          flutter build apk --no-tree-shake-icons
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
          name: android-apk
          if-no-files-found: error
          retention-days: 1


    
  android-e2e-tests:
    name: Run Android E2E Tests
    needs: [build-android-apk]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get apk
        uses: actions/download-artifact@v4.2.1
        id: get-apk
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk

      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 21

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
    
      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.13.1'

      - name: Install requirements
        run: 'pip install -r test/e2e/requirements.txt'
    
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm        

      - name: Install Appium
        run: | 
          npm install -g appium@2.x.x
          appium driver install uiautomator2

      - name: Test the app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '26'
          arch: 'x86_64'
          disable-animations: true
          disable-spellchecker: true
          script: |
            flutter install -d emulator-5554 --debug
            appium&
            (cd test/e2e && exec pytest -s tests --driver Remote --local android)
            
      
